services:
  selfish-backend:
    image: ghcr.io/server-selfish/backend:latest
    container_name: selfish-backend
    restart: unless-stopped
    depends_on:
      - selfish_db
      - selfish_cache
      - selfish_logs
    volumes:
      - ./backend/config.yaml:/config.yaml:ro
      - ./backend/.secret:/.secret:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV=${BACKEND_ENV:-}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID:-}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET:-}
      - AUTH_GITHUB_APP_ID=${AUTH_GITHUB_APP_ID:-}
      - AUTH_GITHUB_APP_SLUG=${AUTH_GITHUB_APP_SLUG:-}
      - AUTH_GITHUB_PRIVATE_KEY_PATH=${AUTH_GITHUB_PRIVATE_KEY_PATH:-}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET:-}
      - OTEL_LOGS_ENABLED=${OTEL_LOGS_ENABLED:-true}
      - OTEL_LOGS_ENDPOINT=${OTEL_LOGS_ENDPOINT:-http://selfish_logs:9428/insert/opentelemetry/v1/logs}
      - OTEL_LOGS_INSECURE=${OTEL_LOGS_INSECURE:-true}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-selfish-backend}
      - OTEL_SERVICE_VERSION=${OTEL_SERVICE_VERSION:-prod}
    networks:
      - selfish-network
